spring:
  application:
    name: "Clematis Authentication API"
    version: 0.0.3-SNAPSHOT

  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1

server:
  forward-headers-strategy: native
  port: 8083

logging:
  file:
    path:
      ${LOGGING_PATH}
  level:
    org.jgroups: INFO
    org.infinispan: INFO
    org.keycloak: INFO
    org.keycloak.services.managers.DefaultBruteForceProtector: DEBUG
    org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner: DEBUG
    org.keycloak.services.managers.UserSessionManager: DEBUG
    org.keycloak.timer.basic: DEBUG

keycloak:
  server:
    contextPath: /auth
