spring:
  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 1

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jmx:
    enabled: true
    url: service:jmx:jmxmp://${JMXMP_HOST}:${JMXMP_PORT}/

server:
  forward-headers-strategy: native
  port: 8083

logging:
  file:
    path:
      ${LOG_PATH}

  level:
    org.jgroups: INFO
    org.infinispan: INFO
    org.keycloak: INFO
    org.keycloak.services.managers.DefaultBruteForceProtector: DEBUG
    org.keycloak.services.scheduled.ClusterAwareScheduledTaskRunner: DEBUG
    org.keycloak.services.managers.UserSessionManager: DEBUG
    org.keycloak.timer.basic: DEBUG

keycloak:
  server:
    contextPath: /auth

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  show-actuator: true