version: '3.7'

services:
    auth-api:
        container_name: clematis-auth-api
        image: clematis.auth.api:latest
        networks:
          - clematis_auth
        env_file:
          - clematis_auth_api.env
        volumes:
          - /home/clematis/auth/logs:/var/log/clematis
        ports:
          - "8083:8083"
          - "15083:5000"
          - "15084:5001"
        restart: unless-stopped

networks:
  clematis_auth:
    driver: bridge
