version: '3.7'

services:
    clematis-auth-api:
        container_name: clematis-auth-api
        image: clematis.auth.api:latest
        networks:
          - clematis_auth
        env_file:
          - .env
        volumes:
          - /home/clematis/auth/logs:/var/log/clematis
        ports:
          - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
          - "15083:5000"
          - "15084:5001"
        restart: unless-stopped
        depends_on:
          - clematis-auth-db

    clematis-auth-db:
      networks:
        - clematis_auth
      container_name: clematis-auth-mysql-db
      image: library/mysql:latest
      volumes:
        - /home/clematis/auth/storage:/var/lib/mysql
      env_file:
        - .env
      ports:
        - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
      environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      restart: unless-stopped

volumes:
  storage:
    name: clematis-auth-mysql-db-store

networks:
  clematis_auth:
    driver: bridge
