version: '3.7'

services:
    auth-api:
        container_name: clematis-auth-api
        image: clematis.auth.api:latest
        networks:
          - clematis
        env_file:
          - clematis_auth_api.env
        volumes:
          - /home/clematis/auth/logs:/var/log/clematis
        ports:
          - "8083:8083"
          - "15083:5000"
          - "15084:5001"
        restart: unless-stopped

    mysql_db:
      networks:
        - clematis
      container_name: clematis_mysql_db
      image: library/mysql:8.0
      mem_reservation: 1G
      volumes:
        - /home/clematis/storage:/opt/data
      env_file:
        - clematis_auth_db.env
        - clematis_auth_db.env.private
      ports:
        - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
      environment:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

networks:
  clematis:
    driver: bridge
